#!/usr/bin/env bash

if [[ -f .env ]]; then
  source .env
  export FIREBASE_API_KEY=$FIREBASE_API_KEY
  export FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
  export FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
  export FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
  export FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
  export FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
else
  export FIREBASE_API_KEY="${FIREBASE_API_KEY}"
  export FIREBASE_AUTH_DOMAIN="${FIREBASE_AUTH_DOMAIN}"
  export FIREBASE_DATABASE_URL="${FIREBASE_DATABASE_URL}"
  export FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID}"
  export FIREBASE_STORAGE_BUCKET="${FIREBASE_STORAGE_BUCKET}"
  export FIREBASE_MESSAGING_SENDER_ID="${FIREBASE_MESSAGING_SENDER_ID}"
fi

yarn run build-with-tests
